require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sale_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SaleItem. As you add validations to SaleItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SaleItem.create! valid_attributes
      get sale_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sale_item = SaleItem.create! valid_attributes
      get sale_item_url(sale_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sale_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sale_item = SaleItem.create! valid_attributes
      get edit_sale_item_url(sale_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SaleItem" do
        expect {
          post sale_items_url, params: { sale_item: valid_attributes }
        }.to change(SaleItem, :count).by(1)
      end

      it "redirects to the created sale_item" do
        post sale_items_url, params: { sale_item: valid_attributes }
        expect(response).to redirect_to(sale_item_url(SaleItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SaleItem" do
        expect {
          post sale_items_url, params: { sale_item: invalid_attributes }
        }.to change(SaleItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sale_items_url, params: { sale_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sale_item" do
        sale_item = SaleItem.create! valid_attributes
        patch sale_item_url(sale_item), params: { sale_item: new_attributes }
        sale_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sale_item" do
        sale_item = SaleItem.create! valid_attributes
        patch sale_item_url(sale_item), params: { sale_item: new_attributes }
        sale_item.reload
        expect(response).to redirect_to(sale_item_url(sale_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sale_item = SaleItem.create! valid_attributes
        patch sale_item_url(sale_item), params: { sale_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sale_item" do
      sale_item = SaleItem.create! valid_attributes
      expect {
        delete sale_item_url(sale_item)
      }.to change(SaleItem, :count).by(-1)
    end

    it "redirects to the sale_items list" do
      sale_item = SaleItem.create! valid_attributes
      delete sale_item_url(sale_item)
      expect(response).to redirect_to(sale_items_url)
    end
  end
end
